spring:
  datasource:
    url: @db_url@
    username: @db_user@
    password: @db_pass@
  h2:
    console:
      enabled: true

  liquibase:
    default-schema: @default.schema@
    change-log: classpath:db/changelog.yml
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: summer_bank
    hibernate:
      ddl-auto: update
app:
  secret-lifetime: @secret_lifetime_days@
