spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  h2:
    console:
      enabled: true

  liquibase:
    change-log: classpath:db/changelog.yml
app:
  secret-lifetime: 120