spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: sa
    password: password
  h2:
    console:
      enabled: true

  liquibase:
    default-schema: summer_bank
    change-log: classpath:db/changelog.yml
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: summer_bank
app:
  secret-lifetime: 120
